<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MenuItem;

class MenuItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            [
                'name' => 'Margherita Pizza',
                'includes' => 'Cheese, Tomato Sauce, Basil',
                'description' => 'Classic cheese and tomato pizza with fresh basil.',
                'category_id' => 1,
                'mrp' => 299,
                'discount' => 10,
                'gst' => 5,
                'is_available' => true,
                'image' => 'menu/margherita.jpg',
            ],
            [
                'name' => 'Veggie Burger',
                'includes' => 'Veg Patty, Lettuce, Tomato, Onion, Cheese',
                'description' => 'Delicious burger with a crispy veggie patty and fresh toppings.',
                'category_id' => 1,
                'mrp' => 199,
                'discount' => 5,
                'gst' => 5,
                'is_available' => true,
                'image' => 'menu/veggie-burger.jpg',
            ],
            [
                'name' => 'Pasta Alfredo',
                'includes' => 'Pasta, Creamy Alfredo Sauce, Parmesan',
                'description' => 'Creamy Alfredo pasta topped with parmesan cheese.',
                'category_id' => 1,
                'mrp' => 249,
                'discount' => 0,
                'gst' => 5,
                'is_available' => true,
                'image' => 'menu/alfredo.jpg',
            ],
            [ 
                'name' => 'Paneer Tikka', 
                'includes' => 'Paneer, Spices, Yogurt', 
                'description' => 'Grilled paneer cubes marinated in spices.', 
                'category_id' => 1, 
                'mrp' => 220, 
                'discount' => 10, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/paneer-tikka.jpg', 
            ],
            [ 
                'name' => 'Chicken Biryani', 
                'includes' => 'Chicken, Basmati Rice, Spices', 
                'description' => 'Aromatic rice with tender chicken pieces.', 
                'category_id' => 1, 
                'mrp' => 320, 
                'discount' => 15, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/chicken-biryani.jpg', 
            ],
            [ 
                'name' => 'Caesar Salad', 
                'includes' => 'Lettuce, Croutons, Parmesan, Caesar Dressing', 
                'description' => 'Classic Caesar salad with fresh ingredients.', 
                'category_id' => 1, 
                'mrp' => 180, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/caesar-salad.jpg', 
            ],
            [ 
                'name' => 'French Fries', 
                'includes' => 'Potatoes, Salt', 
                'description' => 'Crispy golden potato fries.', 
                'category_id' => 1, 
                'mrp' => 99, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/fries.jpg', 
            ],
            [ 
                'name' => 'Butter Chicken', 
                'includes' => 'Chicken, Butter, Tomato Gravy', 
                'description' => 'Rich and creamy butter chicken.', 
                'category_id' => 1, 
                'mrp' => 350, 
                'discount' => 10, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/butter-chicken.jpg', 
            ],
            [ 
                'name' => 'Chole Bhature', 
                'includes' => 'Chickpeas, Spices, Fried Bread', 
                'description' => 'Spicy chickpeas with fluffy fried bread.', 
                'category_id' => 1, 
                'mrp' => 160, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/chole-bhature.jpg', 
            ],
            [ 
                'name' => 'Masala Dosa', 
                'includes' => 'Rice, Potato Masala', 
                'description' => 'Crispy dosa filled with spicy potato.', 
                'category_id' => 1, 
                'mrp' => 140, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/masala-dosa.jpg', 
            ],
            [ 
                'name' => 'Samosa', 
                'includes' => 'Potato, Peas, Spices', 
                'description' => 'Deep-fried pastry with spicy filling.', 
                'category_id' => 1, 
                'mrp' => 30, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/samosa.jpg', 
            ],
            [ 
                'name' => 'Spring Rolls', 
                'includes' => 'Vegetables, Wrapper', 
                'description' => 'Crispy rolls stuffed with veggies.', 
                'category_id' => 1, 
                'mrp' => 90, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/spring-rolls.jpg', 
            ],
            [ 
                'name' => 'Hakka Noodles', 
                'includes' => 'Noodles, Vegetables, Soy Sauce', 
                'description' => 'Stir-fried noodles with veggies.', 
                'category_id' => 1, 
                'mrp' => 120, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/hakka-noodles.jpg', 
            ],
            [ 
                'name' => 'Gulab Jamun', 
                'includes' => 'Milk Solids, Sugar Syrup', 
                'description' => 'Soft sweet balls soaked in syrup.', 
                'category_id' => 1, 
                'mrp' => 60, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/gulab-jamun.jpg', 
            ],
            [ 
                'name' => 'Paneer Butter Masala', 
                'includes' => 'Paneer, Tomato, Butter', 
                'description' => 'Paneer in creamy tomato gravy.', 
                'category_id' => 1, 
                'mrp' => 230, 
                'discount' => 10, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/paneer-butter-masala.jpg', 
            ],
            [ 
                'name' => 'Fish Curry', 
                'includes' => 'Fish, Spices, Coconut Milk', 
                'description' => 'Spicy fish curry with coconut flavor.', 
                'category_id' => 1, 
                'mrp' => 280, 
                'discount' => 5, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/fish-curry.jpg', 
            ],
            [ 
                'name' => 'Egg Curry', 
                'includes' => 'Eggs, Tomato, Spices', 
                'description' => 'Boiled eggs in spicy tomato gravy.', 
                'category_id' => 1, 
                'mrp' => 160, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/egg-curry.jpg', 
            ],
            [ 
                'name' => 'Dal Makhani', 
                'includes' => 'Black Lentils, Butter, Cream', 
                'description' => 'Rich and creamy dal makhani.', 
                'category_id' => 1, 
                'mrp' => 170, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/dal-makhani.jpg', 
            ],
            [ 
                'name' => 'Tandoori Chicken', 
                'includes' => 'Chicken, Yogurt, Spices', 
                'description' => 'Chicken marinated and grilled in tandoor.', 
                'category_id' => 1, 
                'mrp' => 320, 
                'discount' => 10, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/tandoori-chicken.jpg', 
            ],
            [ 
                'name' => 'Club Sandwich', 
                'includes' => 'Bread, Chicken, Lettuce, Tomato, Mayo', 
                'description' => 'Triple layered sandwich with chicken and veggies.', 
                'category_id' => 1, 
                'mrp' => 150, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/club-sandwich.jpg', 
            ],
            [ 
                'name' => 'Egg Fried Rice', 
                'includes' => 'Rice, Egg, Vegetables, Soy Sauce', 
                'description' => 'Fried rice with egg and veggies.', 
                'category_id' => 1, 
                'mrp' => 130, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/egg-fried-rice.jpg', 
            ],
            [ 
                'name' => 'Mutton Rogan Josh', 
                'includes' => 'Mutton, Spices, Yogurt', 
                'description' => 'Kashmiri style mutton curry.', 
                'category_id' => 1, 
                'mrp' => 350, 
                'discount' => 10, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/mutton-rogan-josh.jpg', 
            ],
            [ 
                'name' => 'Veg Manchurian', 
                'includes' => 'Vegetable Balls, Soy Sauce', 
                'description' => 'Fried veggie balls in tangy sauce.', 
                'category_id' => 1, 
                'mrp' => 140, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/veg-manchurian.jpg', 
            ],
            [ 
                'name' => 'Chicken Tikka Masala', 
                'includes' => 'Chicken, Tomato, Spices', 
                'description' => 'Chicken in spicy tomato gravy.', 
                'category_id' => 1, 
                'mrp' => 320, 
                'discount' => 10, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/chicken-tikka-masala.jpg', 
            ],
            [ 
                'name' => 'Greek Salad', 
                'includes' => 'Cucumber, Tomato, Feta, Olives', 
                'description' => 'Fresh salad with feta and olives.', 
                'category_id' => 1, 
                'mrp' => 180, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/greek-salad.jpg', 
            ],
            [ 
                'name' => 'Shahi Paneer', 
                'includes' => 'Paneer, Cream, Spices', 
                'description' => 'Paneer in rich creamy gravy.', 
                'category_id' => 1, 
                'mrp' => 250, 
                'discount' => 10, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/shahi-paneer.jpg', 
            ],
            [ 
                'name' => 'Pepperoni Pizza', 
                'includes' => 'Pepperoni, Cheese, Tomato Sauce', 
                'description' => 'Pizza topped with pepperoni.', 
                'category_id' => 1, 
                'mrp' => 350, 
                'discount' => 10, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/pepperoni.jpg', 
            ],
            [ 
                'name' => 'Chocolate Brownie', 
                'includes' => 'Chocolate, Flour, Sugar', 
                'description' => 'Rich chocolate brownie dessert.', 
                'category_id' => 1, 
                'mrp' => 80, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/brownie.jpg', 
            ],
            [ 
                'name' => 'Falafel Wrap', 
                'includes' => 'Falafel, Pita, Veggies, Sauce', 
                'description' => 'Middle Eastern wrap with falafel.', 
                'category_id' => 1, 
                'mrp' => 120, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/falafel.jpg', 
            ],
            [ 
                'name' => 'Chicken Shawarma', 
                'includes' => 'Chicken, Pita, Veggies, Sauce', 
                'description' => 'Grilled chicken wrap with veggies.', 
                'category_id' => 1, 
                'mrp' => 140, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/shawarma.jpg', 
            ],
            [ 
                'name' => 'Veggie Supreme Pizza', 
                'includes' => 'Veggies, Cheese, Tomato Sauce', 
                'description' => 'Loaded veggie pizza.', 
                'category_id' => 1, 
                'mrp' => 320, 
                'discount' => 10, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/veggie-supreme.jpg', 
            ],
            [ 
                'name' => 'Corn Cheese Balls', 
                'includes' => 'Corn, Cheese, Spices', 
                'description' => 'Crispy fried corn and cheese balls.', 
                'category_id' => 1, 
                'mrp' => 110, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/corn-cheese-balls.jpg', 
            ],
            [ 
                'name' => 'Pav Bhaji', 
                'includes' => 'Vegetables, Spices, Bread', 
                'description' => 'Spicy mashed veggies with soft bread.', 
                'category_id' => 1, 
                'mrp' => 110, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/pav-bhaji.jpg', 
            ],
            [ 
                'name' => 'Rajma Chawal', 
                'includes' => 'Kidney Beans, Rice, Spices', 
                'description' => 'North Indian style kidney beans curry.', 
                'category_id' => 1, 
                'mrp' => 120, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/rajma-chawal.jpg', 
            ],
            [ 
                'name' => 'Mushroom Soup', 
                'includes' => 'Mushroom, Cream, Spices', 
                'description' => 'Creamy mushroom soup.', 
                'category_id' => 1, 
                'mrp' => 90, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/mushroom-soup.jpg', 
            ],
            [ 
                'name' => 'Hot Chocolate', 
                'includes' => 'Milk, Cocoa, Sugar', 
                'description' => 'Warm and comforting hot chocolate.', 
                'category_id' => 1, 
                'mrp' => 70, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/hot-chocolate.jpg', 
            ],
            [ 
                'name' => 'Fruit Salad', 
                'includes' => 'Seasonal Fruits', 
                'description' => 'Freshly cut seasonal fruits.', 
                'category_id' => 1, 
                'mrp' => 80, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/fruit-salad.jpg', 
            ],
            [ 
                'name' => 'Idli Sambhar', 
                'includes' => 'Rice Cakes, Lentil Soup', 
                'description' => 'Steamed idlis with spicy sambhar.', 
                'category_id' => 1, 
                'mrp' => 80, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/idli-sambhar.jpg', 
            ],
            [ 
                'name' => 'Chicken Wings', 
                'includes' => 'Chicken, Spices, Sauce', 
                'description' => 'Spicy and crispy chicken wings.', 
                'category_id' => 1, 
                'mrp' => 180, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/chicken-wings.jpg', 
            ],
            [ 
                'name' => 'Garlic Bread', 
                'includes' => 'Bread, Garlic, Butter', 
                'description' => 'Toasted garlic bread slices.', 
                'category_id' => 1, 
                'mrp' => 80, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/garlic-bread.jpg', 
            ],
            [ 
                'name' => 'Tandoori Paneer Pizza', 
                'includes' => 'Paneer, Tandoori Sauce, Cheese', 
                'description' => 'Pizza with tandoori paneer topping.', 
                'category_id' => 1, 
                'mrp' => 320, 
                'discount' => 10, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/tandoori-paneer-pizza.jpg', 
            ],
            [ 
                'name' => 'Mango Lassi', 
                'includes' => 'Mango, Yogurt, Sugar', 
                'description' => 'Refreshing mango yogurt drink.', 
                'category_id' => 1, 
                'mrp' => 60, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/mango-lassi.jpg', 
            ],
            [ 
                'name' => 'Veg Pulao', 
                'includes' => 'Rice, Vegetables, Spices', 
                'description' => 'Aromatic rice with mixed veggies.', 
                'category_id' => 1, 
                'mrp' => 110, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/veg-pulao.jpg', 
            ],
            [ 
                'name' => 'Chicken Kathi Roll', 
                'includes' => 'Chicken, Paratha, Veggies', 
                'description' => 'Spicy chicken rolled in paratha.', 
                'category_id' => 1, 
                'mrp' => 130, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/chicken-kathi-roll.jpg', 
            ],
            [ 
                'name' => 'Veggie Wrap', 
                'includes' => 'Veggies, Tortilla, Sauce', 
                'description' => 'Healthy wrap with fresh veggies.', 
                'category_id' => 1, 
                'mrp' => 110, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/veggie-wrap.jpg', 
            ],
            [ 
                'name' => 'Dal Tadka', 
                'includes' => 'Lentils, Spices, Ghee', 
                'description' => 'Yellow dal tempered with ghee.', 
                'category_id' => 1, 
                'mrp' => 90, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/dal-tadka.jpg', 
            ],
            [ 
                'name' => 'Tomato Soup', 
                'includes' => 'Tomato, Cream, Spices', 
                'description' => 'Creamy tomato soup.', 
                'category_id' => 1, 
                'mrp' => 70, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/tomato-soup.jpg', 
            ],
            [ 
                'name' => 'Paneer Roll', 
                'includes' => 'Paneer, Paratha, Veggies', 
                'description' => 'Paneer stuffed in soft paratha.', 
                'category_id' => 1, 
                'mrp' => 120, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/paneer-roll.jpg', 
            ],
            [ 
                'name' => 'Onion Rings', 
                'includes' => 'Onion, Batter, Spices', 
                'description' => 'Crispy fried onion rings.', 
                'category_id' => 1, 
                'mrp' => 90, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/onion-rings.jpg', 
            ],
            [ 
                'name' => 'Veggie Delight Sandwich', 
                'includes' => 'Bread, Veggies, Cheese', 
                'description' => 'Sandwich loaded with veggies and cheese.', 
                'category_id' => 1, 
                'mrp' => 100, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/veggie-delight.jpg', 
            ],
            [ 
                'name' => 'Chicken Lollipop', 
                'includes' => 'Chicken, Spices, Sauce', 
                'description' => 'Fried chicken drumettes.', 
                'category_id' => 1, 
                'mrp' => 160, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/chicken-lollipop.jpg', 
            ],
            [ 
                'name' => 'Aloo Tikki', 
                'includes' => 'Potato, Spices, Herbs', 
                'description' => 'Spiced potato patties.', 
                'category_id' => 1, 
                'mrp' => 60, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/aloo-tikki.jpg', 
            ],
            [ 
                'name' => 'Veg Cheese Pizza', 
                'includes' => 'Cheese, Veggies, Tomato Sauce', 
                'description' => 'Pizza loaded with cheese and veggies.', 
                'category_id' => 1, 
                'mrp' => 320, 
                'discount' => 10, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/veg-cheese-pizza.jpg', 
            ],
            [ 
                'name' => 'Chicken Popcorn', 
                'includes' => 'Chicken, Spices, Batter', 
                'description' => 'Crispy chicken popcorn bites.', 
                'category_id' => 1, 
                'mrp' => 110, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/chicken-popcorn.jpg', 
            ],
            [ 
                'name' => 'Veggie Momos', 
                'includes' => 'Veggies, Dough, Spices', 
                'description' => 'Steamed dumplings stuffed with veggies.', 
                'category_id' => 1, 
                'mrp' => 90, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/veggie-momos.jpg', 
            ],
            [ 
                'name' => 'Lemonade', 
                'includes' => 'Lemon, Sugar, Water', 
                'description' => 'Refreshing lemon drink.', 
                'category_id' => 1, 
                'mrp' => 50, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/lemonade.jpg', 
            ],
            [ 
                'name' => 'Cold Coffee', 
                'includes' => 'Coffee, Milk, Sugar', 
                'description' => 'Chilled coffee beverage.', 
                'category_id' => 1, 
                'mrp' => 70, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/cold-coffee.jpg', 
            ],
            [ 
                'name' => 'Veg Hakka Chowmein', 
                'includes' => 'Noodles, Veggies, Soy Sauce', 
                'description' => 'Chinese style stir-fried noodles.', 
                'category_id' => 1, 
                'mrp' => 120, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/hakka-chowmein.jpg', 
            ],
            [ 
                'name' => 'Paneer Pakora', 
                'includes' => 'Paneer, Gram Flour, Spices', 
                'description' => 'Fried paneer fritters.', 
                'category_id' => 1, 
                'mrp' => 100, 
                'discount' => 0, 
                'gst' => 5, 
                'is_available' => true, 
                'image' => 'menu/paneer-pakora.jpg', 
            ],
        ];

        foreach ($items as $item) {
            MenuItem::create($item);
        }
    }
}
